import type { Block, Board, Field, Issue } from '@stormm/process-model'

/** `generated` files are overwritten on every run; `stub` files are created once and belong to the developers. */
export type FileKind = 'generated' | 'stub'

export interface GeneratedFile {
  /** Relative to the repository root, e.g. `stormm/generated/checkout/domain/order/order_gen.go`. */
  path: string
  kind: FileKind
  content: string
}

export interface GenerateOptions {
  /** Where the Go module root lives. Default `stormm/generated/<board id>`. */
  outputRoot?: string
  /** Go import path of that root. Default `<board id>`. Set it when moving the code into an existing module. */
  modulePath?: string
  /** Also emit a go.mod at the output root. Default true; turn it off inside an existing module. */
  goMod?: boolean
}

export interface GenerateResult {
  files: GeneratedFile[]
  issues: Issue[]
}

const HEADER = '// Code generated by Stormm from the process YAML. DO NOT EDIT.\n\n'
const GO_KEYWORDS = new Set(
  'break case chan const continue default defer else fallthrough for func go goto if import interface map package range return select struct switch type var'.split(' '),
)
const PRIMITIVES: Record<string, string> = { string: 'string', number: 'float64', int: 'int', bool: 'bool' }

const pascal = (text: string) => {
  const name = text
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join('')
  return /^[A-Za-z]/.test(name) ? name : `X${name}`
}
const lowerFirst = (s: string) => s[0]!.toLowerCase() + s.slice(1)
const oneLine = (s: string) => s.replace(/\s+/g, ' ').trim()

/** gofmt-style alignment of struct fields: names padded to one column, types padded when a tag follows. */
function structBody(rows: string[][]): string {
  const w0 = Math.max(...rows.map((r) => r[0]!.length))
  const w1 = Math.max(...rows.filter((r) => r[2]).map((r) => r[1]!.length), 0)
  return rows
    .map(([name, type, tag]) => `\t${name.padEnd(w0)} ${tag ? type!.padEnd(w1) + ' ' + tag : type}`)
    .join('\n')
}
const struct = (name: string, rows: string[][]) => (rows.length ? `type ${name} struct {\n${structBody(rows)}\n}` : `type ${name} struct{}`)
const tag = (name: string) => `\`json:"${name}"\``
/** Consecutive one-line funcs: gofmt lines their bodies up. */
const oneLiners = (rows: [string, string][]) => {
  const w = Math.max(...rows.map(([sig]) => sig.length))
  return rows.map(([sig, body]) => `${sig.padEnd(w)} ${body}`).join('\n')
}
/** Go import declaration: standard library group, blank line, then local packages. */
const imports = (std: string[], local: string[]) => {
  const groups = [std, local].filter((g) => g.length)
  const all = groups.flat()
  if (all.length === 1) return `import "${all[0]}"`
  return `import (\n${groups.map((g) => g.map((p) => `\t"${p}"`).join('\n')).join('\n\n')}\n)`
}

interface Aggregate {
  block: Block
  name: string
  pkg: string
  commands: Block[]
  events: Block[]
}

export function generateGo(board: Board, options: GenerateOptions = {}): GenerateResult {
  const issues: Issue[] = []
  const root = (options.outputRoot ?? `stormm/generated/${board.id}`).replace(/\/+$/, '')
  const mod = options.modulePath ?? board.id
  const files: GeneratedFile[] = []
  const put = (path: string, kind: FileKind, content: string) => files.push({ path: `${root}/${path}`, kind, content })
  const issue = (level: Issue['level'], code: string, message: string) => issues.push({ level, code, message })

  // ----- read the structure off the connections -----
  const byId = new Map(board.blocks.map((b) => [b.id, b]))
  const links = board.connections.flatMap((c) => {
    const from = byId.get(c.from)
    const to = byId.get(c.to)
    return from && to ? [{ from, to }] : []
  })
  const aggregates: Aggregate[] = []
  const taken = new Set<string>()
  for (const block of board.blocks.filter((b) => b.kind === 'aggregate')) {
    const name = pascal(block.title)
    let pkg = name.toLowerCase()
    if (GO_KEYWORDS.has(pkg)) pkg += 'agg'
    if (taken.has(pkg)) {
      issue('error', 'codegen/name-clash', `Aggregate "${block.title}" has the same code name as another aggregate (${name}); rename one.`)
      continue
    }
    taken.add(pkg)
    aggregates.push({ block, name, pkg, commands: [], events: [] })
  }
  const owner = (kind: 'command' | 'event', block: Block, agg: Aggregate) => {
    const list = kind === 'command' ? agg.commands : agg.events
    if (aggregates.some((a) => (kind === 'command' ? a.commands : a.events).includes(block))) {
      issue('warning', 'codegen/multiple-aggregates', `${kind === 'command' ? 'Command' : 'Event'} "${block.title}" is connected to more than one aggregate; only the first one gets it.`)
      return
    }
    list.push(block)
  }
  for (const agg of aggregates) {
    for (const { from, to } of links) {
      if (to === agg.block && from.kind === 'command') owner('command', from, agg)
      if (from === agg.block && to.kind === 'event') owner('event', to, agg)
    }
  }
  // Commands handled by, and events recorded by, an external system are outside this code.
  const external = new Set(links.flatMap(({ from, to }) => (to.kind === 'system' && from.kind === 'command' ? [from] : from.kind === 'system' && to.kind === 'event' ? [to] : [])))
  for (const b of board.blocks.filter((b) => !external.has(b))) {
    if (b.kind === 'command' && !aggregates.some((a) => a.commands.includes(b)))
      issue('warning', 'codegen/orphan-command', `Command "${b.title}" does not lead to an aggregate, so no code is generated for it.`)
    if (b.kind === 'event' && !aggregates.some((a) => a.events.includes(b)))
      issue('warning', 'codegen/orphan-event', `Event "${b.title}" is not produced by an aggregate, so no code is generated for it.`)
  }

  // ----- types: primitives map directly, anything else is a value object the developers define -----
  const valueObjects = new Set<string>()
  const goType = (raw: string, where: string): string => {
    const t = raw.trim()
    if (t.endsWith('[]')) return `[]${goType(t.slice(0, -2), where)}`
    if (PRIMITIVES[t]) return PRIMITIVES[t]
    if (/^[A-Za-z][A-Za-z0-9]*$/.test(t)) {
      const name = pascal(t)
      valueObjects.add(name)
      return `domain.${name}`
    }
    issue('warning', 'codegen/unsupported-type', `${where}: type "${raw}" is not a name Go can use, so it is generated as "any".`)
    return 'any'
  }
  const rowsOf = (fields: Field[], where: string) => fields.map((f) => [pascal(f.name), goType(f.type, where), tag(f.name)])

  // ----- domain/domain.go -----
  put(
    'domain/domain.go',
    'generated',
    `${HEADER}package domain

import "errors"

// Event is what every aggregate records on its event stack.
type Event interface {
\tAggregateID() string
\tEventName() string
}

var (
\t// ErrNotAllowed is what a decide hook returns when an invariant refuses the command.
\tErrNotAllowed = errors.New("command not allowed")
\t// ErrWrongAggregate means a decide hook returned an event stamped with another aggregate's ID.
\tErrWrongAggregate = errors.New("event belongs to another aggregate")
)
`,
  )

  for (const agg of aggregates) generateAggregate(agg)

  if (valueObjects.size) {
    put(
      'domain/types.go',
      'stub',
      `package domain

// Value objects named in the storm. Give each one its fields; this file is yours.
${[...valueObjects].sort().map((n) => `type ${n} struct{}`).join('\n')}
`,
    )
  }
  if (options.goMod !== false) put('go.mod', 'generated', `module ${mod}\n\ngo 1.22\n`)

  return { files, issues }

  function generateAggregate(agg: Aggregate) {
    const T = agg.name
    const state = `${lowerFirst(T)}State`
    const marker = `is${T}Event`
    const names = new Set<string>([T, 'Repository'])
    const claim = (block: Block, name: string) => {
      if (names.has(name)) {
        issue('error', 'codegen/name-clash', `"${block.title}" has the same code name (${name}) as something else in ${T}; rename it.`)
        return false
      }
      names.add(name)
      return true
    }
    const commands = agg.commands.filter((c) => claim(c, pascal(c.title)))
    const events = agg.events.filter((e) => claim(e, pascal(e.title)))
    if (!commands.length) issue('warning', 'codegen/no-command', `Aggregate "${agg.block.title}" has no command leading to it yet.`)
    if (!events.length) issue('warning', 'codegen/no-event', `Aggregate "${agg.block.title}" produces no events yet.`)

    const fieldNames = (b: Block) => new Set(b.fields.map((f) => pascal(f.name)))

    // ---- <pkg>_gen.go ----
    const commandTypes = commands.map((c) => {
      const N = pascal(c.title)
      const doc = [`// ${N} is the "${oneLine(c.title)}" command.${c.actor ? ` Performed by ${oneLine(c.actor)}.` : ''}`, ...c.hotspots.map((h) => `// Open question: ${oneLine(h)}`)]
      return `${doc.join('\n')}\n${struct(N, rowsOf(c.fields, `command "${c.title}"`))}`
    })
    const eventTypes = events.map((e) => {
      const N = pascal(e.title)
      const doc = [`// ${N} is the "${oneLine(e.title)}" event.`, ...e.hotspots.map((h) => `// Open question: ${oneLine(h)}`)]
      return `${doc.join('\n')}
${struct(N, [['ID', 'string', tag('id')], ...rowsOf(e.fields, `event "${e.title}"`)])}

${oneLiners([
  [`func (e ${N}) AggregateID() string`, '{ return e.ID }'],
  [`func (e ${N}) EventName() string`, `{ return "${N}" }`],
  [`func (${N}) ${marker}()`, '{}'],
])}`
    })
    const methods = commands.map((c) => {
      const N = pascal(c.title)
      return `func (a *${T}) ${N}(cmd ${N}) error {
\tevents, err := a.decide${N}(cmd)
\tif err != nil {
\t\treturn err
\t}
\tfor _, e := range events {
\t\tif e.AggregateID() != a.id {
\t\t\treturn fmt.Errorf("%w: %s has ID %q, expected %q", domain.ErrWrongAggregate, e.EventName(), e.AggregateID(), a.id)
\t\t}
\t}
\tfor _, e := range events {
\t\ta.apply(e)
\t\ta.pending = append(a.pending, e)
\t}
\treturn nil
}`
    })
    const apply = events.length
      ? `func (a *${T}) apply(e event) {
\tswitch e := e.(type) {
${events.map((e) => `\tcase ${pascal(e.title)}:\n\t\ta.apply${pascal(e.title)}(e)`).join('\n')}
\t}
}`
      : `func (a *${T}) apply(e event) {}`

    put(
      `domain/${agg.pkg}/${agg.pkg}_gen.go`,
      'generated',
      `${HEADER}package ${agg.pkg}

${imports(commands.length ? ['fmt'] : [], [`${mod}/domain`])}

// ${T} is an aggregate root. It changes state only by recording events, and it decides
// through the decide hooks in ${agg.pkg}.go.
${struct(T, [['id', 'string'], ['state', state], ['pending', '[]domain.Event']])}

// event is sealed: only the events generated in this package can be recorded on ${T}.
type event interface {
\tdomain.Event
\t${marker}()
}

// Repository is a port: the domain defines it, an adapter implements it.
type Repository interface {
\tLoad(id string) (*${T}, error) // an unknown id yields a new, empty aggregate
\tSave(a *${T}) error
}

func New(id string) *${T} { return &${T}{id: id} }

// Rehydrate rebuilds the aggregate by replaying its event stream.
func Rehydrate(id string, history []domain.Event) *${T} {
\ta := New(id)
\tfor _, e := range history {
\t\tif ev, ok := e.(event); ok {
\t\t\ta.apply(ev)
\t\t}
\t}
\treturn a
}

func (a *${T}) ID() string { return a.id }

func (a *${T}) PendingEvents() []domain.Event { return append([]domain.Event(nil), a.pending...) }

func (a *${T}) PullEvents() []domain.Event {
\te := a.pending
\ta.pending = nil
\treturn e
}

${apply}
${[...commandTypes, ...eventTypes, ...methods].map((s) => `\n${s}\n`).join('')}`.replace(/\n{3,}/g, '\n\n'),
    )

    // ---- <pkg>.go: yours, created once ----
    const single = events.length === 1 ? events[0]! : undefined
    const needsFmt = commands.some(() => !single)
    const stubBody = (c: Block) => {
      const N = pascal(c.title)
      if (!single) return `\t// TODO: decide when ${N} is allowed and which event happens.\n\treturn nil, fmt.Errorf("%w: ${N} is not implemented", domain.ErrNotAllowed)`
      const own = fieldNames(c)
      const copy = single.fields.map((f) => pascal(f.name)).filter((n) => own.has(n)).map((n) => `, ${n}: cmd.${n}`).join('')
      return `\t// TODO: add the invariants for ${N}: return domain.ErrNotAllowed when the command must be refused.\n\treturn []event{${pascal(single.title)}{ID: a.id${copy}}}, nil`
    }
    put(
      `domain/${agg.pkg}/${agg.pkg}.go`,
      'stub',
      `package ${agg.pkg}

${needsFmt ? imports(['fmt'], [`${mod}/domain`]) + '\n' : ''}
// ${state} is yours: add the fields your invariants need, and set them in the apply hooks.
type ${state} struct{}
${commands.map((c) => `
// decide${pascal(c.title)} holds the invariants of "${oneLine(c.title)}". Return the events that happen, or an error.
func (a *${T}) decide${pascal(c.title)}(cmd ${pascal(c.title)}) ([]event, error) {
${stubBody(c)}
}
`).join('')}${events.map((e) => `
// apply${pascal(e.title)} updates the state when "${oneLine(e.title)}" has happened. It must not fail.
func (a *${T}) apply${pascal(e.title)}(e ${pascal(e.title)}) {}
`).join('')}`.replace(/\n{3,}/g, '\n\n'),
    )

    // ---- <pkg>_gen_test.go: checks that hold whatever the hooks do ----
    if (commands.length) {
      put(
        `domain/${agg.pkg}/${agg.pkg}_gen_test.go`,
        'generated',
        `${HEADER}package ${agg.pkg}

${imports(['errors', 'testing'], [`${mod}/domain`])}

// Whatever the decide hooks do, a command either succeeds or is refused with domain.ErrNotAllowed;
// the events it records belong to this aggregate, and replaying them creates no new pending events.
func TestCommandsHonourTheContract(t *testing.T) {
\tcalls := []struct {
\t\tname string
\t\trun  func(*${T}) error
\t}{
${commands.map((c) => `\t\t{"${pascal(c.title)}", func(a *${T}) error { return a.${pascal(c.title)}(${pascal(c.title)}{}) }},`).join('\n')}
\t}
\tfor _, c := range calls {
\t\tt.Run(c.name, func(t *testing.T) {
\t\t\ta := New("t")
\t\t\tif err := c.run(a); err != nil {
\t\t\t\tif errors.Is(err, domain.ErrNotAllowed) {
\t\t\t\t\tt.Skip("refused by an invariant for an empty command")
\t\t\t\t}
\t\t\t\tt.Fatal(err)
\t\t\t}
\t\t\tfor _, e := range a.PendingEvents() {
\t\t\t\tif e.AggregateID() != "t" {
\t\t\t\t\tt.Fatalf("%s has ID %q, want %q", e.EventName(), e.AggregateID(), "t")
\t\t\t\t}
\t\t\t}
\t\t\tif got := Rehydrate("t", a.PendingEvents()).PendingEvents(); len(got) != 0 {
\t\t\t\tt.Fatalf("rehydrating recorded %d new events", len(got))
\t\t\t}
\t\t})
\t}
}
`,
      )
    }
  }
}
